# Generated by Django 5.2.3 on 2025-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="blog/image", verbose_name="Изображение"),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("publication_attribute", models.BooleanField(verbose_name="Признак публикации")),
                ("number_of_views", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["title", "created_at", "number_of_views"],
            },
        ),
    ]
