# Generated by Django 5.2.3 on 2025-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/image", verbose_name="Изображение"),
        ),
    ]
