# Generated by Django 5.2.3 on 2025-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="catalog/foto", verbose_name="Фото продукта"),
        ),
    ]
