# Generated by Django 5.2.3 on 2025-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_attribute",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
