# Generated by Django 5.2.3 on 2025-07-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_publication_attribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
